version: '3.9'

services:
  gitlab-ci-dashboard:
    image: larscom/gitlab-ci-dashboard:dev
    build:
      context: .
      args:
        VERSION: larscom/gitlab-ci-dashboard:dev
    env_file:
      - ./api/.local.env
    ports:
      - '8080:8080'
