services:
  gitlab-ci-dashboard:
    image: larscom/gitlab-ci-dashboard
    build:
      context: .
      args:
        VERSION_ARG: docker
    env_file:
      - ./api/.env
    # volumes:
    #  - ./api/config.toml:/app/config.toml
    #  - ./api/certs/ca.crt:/app/certs/ca.crt
    environment:
      - 'TZ=Europe/Amsterdam'
    ports:
      - '8080:8080'
