version: '3.9'

services:
  gitlab-ci-dashboard:
    image: larscom/gitlab-ci-dashboard
    build:
      context: .
      args:
        VERSION_ARG: 1
    env_file:
      - .env
    environment:
      - "TZ=Europe/Amsterdam"
    ports:
      - '8080:8080'
