services:
  gitlab-ci-dashboard:
    image: larscom/gitlab-ci-dashboard
    build:
      context: .
      args:
        VERSION_ARG: docker
    env_file:
      - ./api/.env
    environment:
      - 'TZ=Europe/Amsterdam'
    ports:
      - '8080:8080'
