name: docker-publish
'on':
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: larscom/gitlab-ci-dashboard:latest,larscom/gitlab-ci-dashboard:${{ github.ref_name }}
      -
        name: Update description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: larscom/gitlab-ci-dashboard
          short-description: ${{ github.event.repository.description }}
