name: master

'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_and_publish_dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build/Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: larscom/gitlab-ci-dashboard:master
          build-args: "VERSION=larscom/gitlab-ci-dashboard:master"

  build_and_publish_gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}'
      -
        name: Build/Push to Google Cloud Registry
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: gitlab-ci-dashboard-370412
          image_name: larscom/gitlab-ci-dashboard
          image_tag: master
          build_args: "VERSION=larscom/gitlab-ci-dashboard:master"
      -
        name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: 'gcr.io/gitlab-ci-dashboard-370412/larscom/gitlab-ci-dashboard:master'
          service: 'gitlab-ci-dashboard'
          region: 'europe-west4'
